Homework18
AlexandraYushko/Blog pull request #1
Opened 2024-08-06 14:09 UTC by AlexandraYushko

This is a blogging platform
Scripts are written here to create tables, fill them in and delete them

2024-08-16 14:00 UTC, Willynick requested changes

2024-08-16 14:00 UTC, Willynick commented on .gitignore
> +.idea/modules.xml
Нужно добавить папку .idea полностью в исключение, потому что у тебя файлы лишнию добавляются

2024-08-16 14:00 UTC, Willynick commented on src/main/java/org/example/Main.java
> +}
В конце каждого файла в программе должна быть пустая строка

2024-08-16 14:00 UTC, Willynick commented on src/main/resources/db.changelog/insert-changeset-table.sql
> +insert into tags(id, "name") values (1, 'олимпиада'),
Файл "Снимок экрана ..." нужно преименовать во что-то нормальное, отражающее что изображено на картинке и на англ. языке

2024-08-16 14:00 UTC, Willynick commented on src/main/resources/db.changelog/create-changeset-table.sql
> +    author_id bigint references "users"(id),
FOREIGN KEY ключевые слова здесь и дальше не надо?

2024-09-05 12:49 UTC, AlexandraYushko commented on src/main/resources/db.changelog/create-changeset-table.sql
> +    author_id bigint references "users"(id),
даже если ключ слова FOREIGN KEY не указаны, то бд автоматически понимает и устанавливает необходимые ограничения внешнего ключа

2024-09-09 14:15 UTC, Willynick commented on .gitignore
> +.idea/modules.xml
Не сделано. Поднимаю

2024-09-09 14:15 UTC, Willynick commented on src/main/java/org/example/Main.java
> +}
Не сделано. Поднимаю

2024-10-16 14:41 UTC, merged